<?php
declare(strict_types=1);

namespace Crustum\Mongo\Migration\Command;

use Cake\Command\Command;
use Cake\Console\Arguments;
use Cake\Console\ConsoleIo;
use Cake\Console\ConsoleOptionParser;
use Cake\Datasource\ConnectionManager;
use Crustum\Mongo\Database\Connection;
use Crustum\Mongo\Migration\SchemaDumper;
use RuntimeException;

/**
 * Dumps the live Mongo schema to `config/schema_mongo.php`.
 *
 * The dumped file is the "desired" schema used by `migrations diff` and as the
 * file-backed prod schema (avoids per-request introspection).
 */
class DumpCommand extends Command
{
    /**
     * @inheritDoc
     */
    public static function getDescription(): string
    {
        return 'Dump the current Mongo schema to config/schema_mongo.php.';
    }

    /**
     * The default name added to the application command list.
     *
     * @return string
     */
    public static function defaultName(): string
    {
        return 'mongo schema dump';
    }

    /**
     * Configure the option parser.
     *
     * @param \Cake\Console\ConsoleOptionParser $parser The option parser to configure
     * @return \Cake\Console\ConsoleOptionParser
     */
    protected function buildOptionParser(ConsoleOptionParser $parser): ConsoleOptionParser
    {
        $parser->setDescription([
            'Dump the current Mongo schema to config/schema_mongo.php',
            '',
            '<info>schema dump</info>',
            '<info>schema dump --connection mongo</info>',
        ])->addOption('connection', [
            'short' => 'c',
            'help' => 'The datasource connection to use',
            'default' => 'default',
        ])->addOption('path', [
            'help' => 'The output file path (default: config/schema_mongo.php)',
        ]);

        return $parser;
    }

    /**
     * Execute the command.
     *
     * @param \Cake\Console\Arguments $args The command arguments
     * @param \Cake\Console\ConsoleIo $io The console io
     * @return int|null The exit code or null for success
     */
    public function execute(Arguments $args, ConsoleIo $io): ?int
    {
        $connectionName = (string)$args->getOption('connection');
        $connection = ConnectionManager::get($connectionName);
        if (!$connection instanceof Connection) {
            throw new RuntimeException(sprintf(
                'Connection `%s` is not a %s instance.',
                $connectionName,
                Connection::class,
            ));
        }

        $dumper = new SchemaDumper($connection);
        $schema = $dumper->dumpAll();

        $path = $args->getOption('path');
        $file = is_string($path) ? $path : CONFIG . 'schema_mongo.php';

        $content = "<?php\ndeclare(strict_types=1);\n\n" .
            "// Generated by `schema dump`. Do not edit by hand.\n" .
            'return ' . var_export($schema, true) . ";\n";

        if (file_put_contents($file, $content) === false) {
            throw new RuntimeException(sprintf('Could not write schema dump to `%s`.', $file));
        }

        $io->success(sprintf('Dumped schema for %d collections to `%s`.', count($schema), $file));

        return self::CODE_SUCCESS;
    }
}
